# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OrbCorgui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 744)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.samplingIntervalSLabel = QtWidgets.QLabel(self.centralwidget)
        self.samplingIntervalSLabel.setObjectName("samplingIntervalSLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.samplingIntervalSLabel)
        self.samplingIntervalSLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.samplingIntervalSLineEdit.setObjectName("samplingIntervalSLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.samplingIntervalSLineEdit)
        self.correctorAccuracyUmLabel = QtWidgets.QLabel(self.centralwidget)
        self.correctorAccuracyUmLabel.setObjectName("correctorAccuracyUmLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.correctorAccuracyUmLabel)
        self.correctorAccuracyUmLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.correctorAccuracyUmLineEdit.setObjectName("correctorAccuracyUmLineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.correctorAccuracyUmLineEdit)
        self.sampPerStepLabel = QtWidgets.QLabel(self.centralwidget)
        self.sampPerStepLabel.setObjectName("sampPerStepLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sampPerStepLabel)
        self.sampPerStepLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sampPerStepLineEdit.setObjectName("sampPerStepLineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sampPerStepLineEdit)
        self.gridLayout.addLayout(self.formLayout_3, 4, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 5, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 3)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 4, 1, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout.addWidget(self.listWidget_2, 4, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Orbit Correct"))
        self.label_6.setText(_translate("MainWindow", "Method"))
        self.comboBox.setItemText(0, _translate("MainWindow", "one-to-one"))
        self.comboBox.setItemText(1, _translate("MainWindow", "global"))
        self.samplingIntervalSLabel.setText(_translate("MainWindow", "sampling interval(s)"))
        self.correctorAccuracyUmLabel.setText(_translate("MainWindow", "corrector accuracy(um)"))
        self.sampPerStepLabel.setText(_translate("MainWindow", "samp per step"))
        self.pushButton_3.setText(_translate("MainWindow", "stop"))
        self.pushButton_4.setText(_translate("MainWindow", "start"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "BPM03"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "BPM04"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "BPM05"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "BPM06"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "BPM07"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "BPM08"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "BPM09"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "BPM10"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "BPM11"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "BPM12"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "BPM13"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "BPM14"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "BPM15"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "BPM16"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "BPM17"))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "BPM18"))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "BPM19"))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "BPM20"))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "BPM21"))
        item = self.listWidget.item(19)
        item.setText(_translate("MainWindow", "BPM22"))
        item = self.listWidget.item(20)
        item.setText(_translate("MainWindow", "BPM23"))
        item = self.listWidget.item(21)
        item.setText(_translate("MainWindow", "BPM24"))
        item = self.listWidget.item(22)
        item.setText(_translate("MainWindow", "BPM25"))
        item = self.listWidget.item(23)
        item.setText(_translate("MainWindow", "BPM26"))
        item = self.listWidget.item(24)
        item.setText(_translate("MainWindow", "BPM27"))
        item = self.listWidget.item(25)
        item.setText(_translate("MainWindow", "BPM28"))
        item = self.listWidget.item(26)
        item.setText(_translate("MainWindow", "BPM29"))
        item = self.listWidget.item(27)
        item.setText(_translate("MainWindow", "BPM30"))
        item = self.listWidget.item(28)
        item.setText(_translate("MainWindow", "BPM31"))
        item = self.listWidget.item(29)
        item.setText(_translate("MainWindow", "BPM32"))
        item = self.listWidget.item(30)
        item.setText(_translate("MainWindow", "BPM33"))
        item = self.listWidget.item(31)
        item.setText(_translate("MainWindow", "BPM34"))
        item = self.listWidget.item(32)
        item.setText(_translate("MainWindow", "BPM35"))
        item = self.listWidget.item(33)
        item.setText(_translate("MainWindow", "BPM36"))
        item = self.listWidget.item(34)
        item.setText(_translate("MainWindow", "BPM37"))
        item = self.listWidget.item(35)
        item.setText(_translate("MainWindow", "BPM38"))
        item = self.listWidget.item(36)
        item.setText(_translate("MainWindow", "BPM39"))
        item = self.listWidget.item(37)
        item.setText(_translate("MainWindow", "BPM40"))
        item = self.listWidget.item(38)
        item.setText(_translate("MainWindow", "BPM41"))
        item = self.listWidget.item(39)
        item.setText(_translate("MainWindow", "BPM42"))
        item = self.listWidget.item(40)
        item.setText(_translate("MainWindow", "BPM43"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("MainWindow", "cor zero"))
        self.pushButton.setText(_translate("MainWindow", "Measure Response"))
