meta:
  name: demo_task
  machine: offline-test-function
  description: ''
  tags:
  - gui
  - offline
backend:
  type: offline
  bounds:
  - - 0.0
    - 1.0
  - - 0.0
    - 1.0
  bounds_mode: absolute
  kwargs:
    func: task_service:wrapped
    x0:
    - 0.5
    - 0.5
    combine_mode: weighted_sum
    variable_names:
    - x0
    - x1
optimizer:
  name: bo
  kwargs:
    n_init: 5
    n_iter: 95
    random_state: 0
    verbose: true
    device: cpu
    kernel_type: matern
    gp_restarts: 5
    acq: ucb
    acq_optimizer: optimize_acqf
    acq_para: 3.0
    acq_opt_kwargs:
      num_restarts: 8
      raw_samples: 256
      n_candidates: 8192
    acq_para_kwargs:
      beta_strategy: inv_decay
      beta_lam: 0.01
runtime:
  save_history: true
  history_path: save/demo_task_history.dat
  plot_convergence: false
  plot_path: save/demo_task_plot.png
  set_best: false
  restore_initial_on_error: true
  restore_initial_on_keyboard_interrupt: true
  verbose: true
