#!/bin/bash
#./cleanUp
elegant one.ele

## twiss
sddsprintout one.twi twissx.DAT -col=s -col=betax -col=alphax -col=etax -col=etaxp 
sddsprintout one.twi twissy.DAT -col=s -col=betay -col=alphay -col=etay -col=etayp

## beam
# 6Ddata
rm -f beam6D*.DAT
sdds2stream W00.out    -col=x,xp,y,yp,t,p >> beam6D_start.DAT 
sdds2stream W33.out    -col=x,xp,y,yp,t,p >> beam6D_middle.DAT 
#sdds2stream wsep1.out  -col=x,xp,y,yp,t,p >> beam6D_final.DAT 


# beamsize
#sddsprintout one2.sig beamszie.DAT -col=s -col=Sx -col=Sy

#enxy
#sddsprintout one2.sig ENXY.DAT -col=s -col=enx -col=eny

#energy/energy spread
#sddsprintout one2.sig ENSP.DAT -col=s -col=Sdelta
#sddsprintout one2.cen Pcentral.DAT -col=s -col=pCentral

## cen
sddsprintout one.cen Cen.DAT -col=s -col=Cx -col=Cy