# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gotacc/gui/ui/dialog_algorithm_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlgorithmDetailDialog(object):
    def setupUi(self, AlgorithmDetailDialog):
        AlgorithmDetailDialog.setObjectName("AlgorithmDetailDialog")
        AlgorithmDetailDialog.resize(820, 520)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(AlgorithmDetailDialog)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.label_summary = QtWidgets.QLabel(AlgorithmDetailDialog)
        self.label_summary.setWordWrap(True)
        self.label_summary.setObjectName("label_summary")
        self.verticalLayout_main.addWidget(self.label_summary)
        self.tableWidget_dynamicParams = QtWidgets.QTableWidget(AlgorithmDetailDialog)
        self.tableWidget_dynamicParams.setObjectName("tableWidget_dynamicParams")
        self.tableWidget_dynamicParams.setColumnCount(4)
        self.tableWidget_dynamicParams.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dynamicParams.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dynamicParams.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dynamicParams.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dynamicParams.setHorizontalHeaderItem(3, item)
        self.verticalLayout_main.addWidget(self.tableWidget_dynamicParams)
        self.buttonBox = QtWidgets.QDialogButtonBox(AlgorithmDetailDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_main.addWidget(self.buttonBox)

        self.retranslateUi(AlgorithmDetailDialog)
        QtCore.QMetaObject.connectSlotsByName(AlgorithmDetailDialog)

    def retranslateUi(self, AlgorithmDetailDialog):
        _translate = QtCore.QCoreApplication.translate
        AlgorithmDetailDialog.setWindowTitle(_translate("AlgorithmDetailDialog", "Algorithm Detail"))
        self.label_summary.setText(_translate("AlgorithmDetailDialog", "Algorithm parameters"))
        item = self.tableWidget_dynamicParams.horizontalHeaderItem(0)
        item.setText(_translate("AlgorithmDetailDialog", "Parameter"))
        item = self.tableWidget_dynamicParams.horizontalHeaderItem(1)
        item.setText(_translate("AlgorithmDetailDialog", "Value"))
        item = self.tableWidget_dynamicParams.horizontalHeaderItem(2)
        item.setText(_translate("AlgorithmDetailDialog", "Type"))
        item = self.tableWidget_dynamicParams.horizontalHeaderItem(3)
        item.setText(_translate("AlgorithmDetailDialog", "Description"))
