# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gotacc/gui/ui/dialog_pv_monitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PVMonitorDialog(object):
    def setupUi(self, PVMonitorDialog):
        PVMonitorDialog.setObjectName("PVMonitorDialog")
        PVMonitorDialog.resize(900, 560)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(PVMonitorDialog)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.label_status = QtWidgets.QLabel(PVMonitorDialog)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_main.addWidget(self.label_status)
        self.tableWidget_pvs = QtWidgets.QTableWidget(PVMonitorDialog)
        self.tableWidget_pvs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_pvs.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_pvs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_pvs.setObjectName("tableWidget_pvs")
        self.tableWidget_pvs.setColumnCount(5)
        self.tableWidget_pvs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pvs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pvs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pvs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pvs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pvs.setHorizontalHeaderItem(4, item)
        self.verticalLayout_main.addWidget(self.tableWidget_pvs)
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(PVMonitorDialog)
        self.plainTextEdit_log.setReadOnly(True)
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.verticalLayout_main.addWidget(self.plainTextEdit_log)
        self.horizontalLayout_actions = QtWidgets.QHBoxLayout()
        self.horizontalLayout_actions.setObjectName("horizontalLayout_actions")
        self.pushButton_refresh = QtWidgets.QPushButton(PVMonitorDialog)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout_actions.addWidget(self.pushButton_refresh)
        self.pushButton_readSelected = QtWidgets.QPushButton(PVMonitorDialog)
        self.pushButton_readSelected.setObjectName("pushButton_readSelected")
        self.horizontalLayout_actions.addWidget(self.pushButton_readSelected)
        self.pushButton_readAll = QtWidgets.QPushButton(PVMonitorDialog)
        self.pushButton_readAll.setObjectName("pushButton_readAll")
        self.horizontalLayout_actions.addWidget(self.pushButton_readAll)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_actions.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(PVMonitorDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_actions.addWidget(self.buttonBox)
        self.verticalLayout_main.addLayout(self.horizontalLayout_actions)

        self.retranslateUi(PVMonitorDialog)
        QtCore.QMetaObject.connectSlotsByName(PVMonitorDialog)

    def retranslateUi(self, PVMonitorDialog):
        _translate = QtCore.QCoreApplication.translate
        PVMonitorDialog.setWindowTitle(_translate("PVMonitorDialog", "PV Monitor"))
        self.label_status.setText(_translate("PVMonitorDialog", "Configure an online EPICS task, then refresh the PV list or read values."))
        item = self.tableWidget_pvs.horizontalHeaderItem(0)
        item.setText(_translate("PVMonitorDialog", "Role"))
        item = self.tableWidget_pvs.horizontalHeaderItem(1)
        item.setText(_translate("PVMonitorDialog", "Name"))
        item = self.tableWidget_pvs.horizontalHeaderItem(2)
        item.setText(_translate("PVMonitorDialog", "PV Name"))
        item = self.tableWidget_pvs.horizontalHeaderItem(3)
        item.setText(_translate("PVMonitorDialog", "Last Value"))
        item = self.tableWidget_pvs.horizontalHeaderItem(4)
        item.setText(_translate("PVMonitorDialog", "Status"))
        self.pushButton_refresh.setText(_translate("PVMonitorDialog", "Refresh List"))
        self.pushButton_readSelected.setText(_translate("PVMonitorDialog", "Read Selected"))
        self.pushButton_readAll.setText(_translate("PVMonitorDialog", "Read All"))
