# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gotacc/gui/ui/dialog_policy_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PolicyEditorDialog(object):
    def setupUi(self, PolicyEditorDialog):
        PolicyEditorDialog.setObjectName("PolicyEditorDialog")
        PolicyEditorDialog.resize(760, 520)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(PolicyEditorDialog)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.label_intro = QtWidgets.QLabel(PolicyEditorDialog)
        self.label_intro.setWordWrap(True)
        self.label_intro.setObjectName("label_intro")
        self.verticalLayout_main.addWidget(self.label_intro)
        self.formLayout_policies = QtWidgets.QFormLayout()
        self.formLayout_policies.setObjectName("formLayout_policies")
        self.label_writePolicy = QtWidgets.QLabel(PolicyEditorDialog)
        self.label_writePolicy.setObjectName("label_writePolicy")
        self.formLayout_policies.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_writePolicy)
        self.comboBox_writePolicy = QtWidgets.QComboBox(PolicyEditorDialog)
        self.comboBox_writePolicy.setObjectName("comboBox_writePolicy")
        self.comboBox_writePolicy.addItem("")
        self.comboBox_writePolicy.addItem("")
        self.formLayout_policies.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_writePolicy)
        self.label_objectivePolicy = QtWidgets.QLabel(PolicyEditorDialog)
        self.label_objectivePolicy.setObjectName("label_objectivePolicy")
        self.formLayout_policies.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_objectivePolicy)
        self.comboBox_objectivePolicy = QtWidgets.QComboBox(PolicyEditorDialog)
        self.comboBox_objectivePolicy.setObjectName("comboBox_objectivePolicy")
        self.comboBox_objectivePolicy.addItem("")
        self.comboBox_objectivePolicy.addItem("")
        self.comboBox_objectivePolicy.addItem("")
        self.formLayout_policies.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_objectivePolicy)
        self.label_targetCol = QtWidgets.QLabel(PolicyEditorDialog)
        self.label_targetCol.setObjectName("label_targetCol")
        self.formLayout_policies.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_targetCol)
        self.spinBox_targetCol = QtWidgets.QSpinBox(PolicyEditorDialog)
        self.spinBox_targetCol.setMaximum(999)
        self.spinBox_targetCol.setObjectName("spinBox_targetCol")
        self.formLayout_policies.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_targetCol)
        self.verticalLayout_main.addLayout(self.formLayout_policies)
        self.groupBox_kwargs = QtWidgets.QGroupBox(PolicyEditorDialog)
        self.groupBox_kwargs.setObjectName("groupBox_kwargs")
        self.verticalLayout_kwargs = QtWidgets.QVBoxLayout(self.groupBox_kwargs)
        self.verticalLayout_kwargs.setObjectName("verticalLayout_kwargs")
        self.plainTextEdit_kwargs = QtWidgets.QPlainTextEdit(self.groupBox_kwargs)
        self.plainTextEdit_kwargs.setObjectName("plainTextEdit_kwargs")
        self.verticalLayout_kwargs.addWidget(self.plainTextEdit_kwargs)
        self.verticalLayout_main.addWidget(self.groupBox_kwargs)
        self.label_hint = QtWidgets.QLabel(PolicyEditorDialog)
        self.label_hint.setWordWrap(True)
        self.label_hint.setObjectName("label_hint")
        self.verticalLayout_main.addWidget(self.label_hint)
        self.plainTextEdit_preview = QtWidgets.QPlainTextEdit(PolicyEditorDialog)
        self.plainTextEdit_preview.setReadOnly(True)
        self.plainTextEdit_preview.setObjectName("plainTextEdit_preview")
        self.verticalLayout_main.addWidget(self.plainTextEdit_preview)
        self.buttonBox = QtWidgets.QDialogButtonBox(PolicyEditorDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_main.addWidget(self.buttonBox)

        self.retranslateUi(PolicyEditorDialog)
        QtCore.QMetaObject.connectSlotsByName(PolicyEditorDialog)

    def retranslateUi(self, PolicyEditorDialog):
        _translate = QtCore.QCoreApplication.translate
        PolicyEditorDialog.setWindowTitle(_translate("PolicyEditorDialog", "Policy Editor"))
        self.label_intro.setText(_translate("PolicyEditorDialog", "Edit machine-side write/objective policy settings and apply them back to the Machine page."))
        self.label_writePolicy.setText(_translate("PolicyEditorDialog", "Write Policy"))
        self.comboBox_writePolicy.setItemText(0, _translate("PolicyEditorDialog", "none"))
        self.comboBox_writePolicy.setItemText(1, _translate("PolicyEditorDialog", "equal"))
        self.label_objectivePolicy.setText(_translate("PolicyEditorDialog", "Objective Policy"))
        self.comboBox_objectivePolicy.setItemText(0, _translate("PolicyEditorDialog", "none"))
        self.comboBox_objectivePolicy.setItemText(1, _translate("PolicyEditorDialog", "fel_energy_guard"))
        self.comboBox_objectivePolicy.setItemText(2, _translate("PolicyEditorDialog", "zero_guard"))
        self.label_targetCol.setText(_translate("PolicyEditorDialog", "Target Column"))
        self.groupBox_kwargs.setTitle(_translate("PolicyEditorDialog", "Objective Policy Kwargs (JSON)"))
        self.label_hint.setText(_translate("PolicyEditorDialog", "`equal` write policy uses the Machine page write-link table. The dialog edits policy selectors and JSON only."))
