# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gotacc/gui/ui/dialog_pv_library_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PVLibrarySelectorDialog(object):
    def setupUi(self, PVLibrarySelectorDialog):
        PVLibrarySelectorDialog.setObjectName("PVLibrarySelectorDialog")
        PVLibrarySelectorDialog.resize(960, 620)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(PVLibrarySelectorDialog)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.label_intro = QtWidgets.QLabel(PVLibrarySelectorDialog)
        self.label_intro.setWordWrap(True)
        self.label_intro.setObjectName("label_intro")
        self.verticalLayout_main.addWidget(self.label_intro)
        self.horizontalLayout_filter = QtWidgets.QHBoxLayout()
        self.horizontalLayout_filter.setObjectName("horizontalLayout_filter")
        self.label_search = QtWidgets.QLabel(PVLibrarySelectorDialog)
        self.label_search.setObjectName("label_search")
        self.horizontalLayout_filter.addWidget(self.label_search)
        self.lineEdit_filter = QtWidgets.QLineEdit(PVLibrarySelectorDialog)
        self.lineEdit_filter.setObjectName("lineEdit_filter")
        self.horizontalLayout_filter.addWidget(self.lineEdit_filter)
        self.verticalLayout_main.addLayout(self.horizontalLayout_filter)
        self.label_summary = QtWidgets.QLabel(PVLibrarySelectorDialog)
        self.label_summary.setWordWrap(True)
        self.label_summary.setObjectName("label_summary")
        self.verticalLayout_main.addWidget(self.label_summary)
        self.tableWidget_library = QtWidgets.QTableWidget(PVLibrarySelectorDialog)
        self.tableWidget_library.setObjectName("tableWidget_library")
        self.tableWidget_library.setColumnCount(5)
        self.tableWidget_library.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_library.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_library.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_library.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_library.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_library.setHorizontalHeaderItem(4, item)
        self.verticalLayout_main.addWidget(self.tableWidget_library)
        self.buttonBox = QtWidgets.QDialogButtonBox(PVLibrarySelectorDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_main.addWidget(self.buttonBox)

        self.retranslateUi(PVLibrarySelectorDialog)
        QtCore.QMetaObject.connectSlotsByName(PVLibrarySelectorDialog)

    def retranslateUi(self, PVLibrarySelectorDialog):
        _translate = QtCore.QCoreApplication.translate
        PVLibrarySelectorDialog.setWindowTitle(_translate("PVLibrarySelectorDialog", "PV Library Selector"))
        self.label_intro.setText(_translate("PVLibrarySelectorDialog", "Choose one or more PV rows from the loaded machine library."))
        self.label_search.setText(_translate("PVLibrarySelectorDialog", "Search"))
        self.lineEdit_filter.setPlaceholderText(_translate("PVLibrarySelectorDialog", "filter by name, PV, readback, group or note..."))
        self.label_summary.setText(_translate("PVLibrarySelectorDialog", "No machine PV library loaded."))
        item = self.tableWidget_library.horizontalHeaderItem(0)
        item.setText(_translate("PVLibrarySelectorDialog", "Name"))
        item = self.tableWidget_library.horizontalHeaderItem(1)
        item.setText(_translate("PVLibrarySelectorDialog", "PV Name"))
        item = self.tableWidget_library.horizontalHeaderItem(2)
        item.setText(_translate("PVLibrarySelectorDialog", "Readback"))
        item = self.tableWidget_library.horizontalHeaderItem(3)
        item.setText(_translate("PVLibrarySelectorDialog", "Group"))
        item = self.tableWidget_library.horizontalHeaderItem(4)
        item.setText(_translate("PVLibrarySelectorDialog", "Note"))
