# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1801, 950)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.X_Plane = QtWidgets.QWidget()
        self.X_Plane.setObjectName("X_Plane")
        self.gridLayout = QtWidgets.QGridLayout(self.X_Plane)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.X_Plane)
        self.widget_4.setObjectName("widget_4")
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setGeometry(QtCore.QRect(180, 120, 91, 16))
        self.label_12.setObjectName("label_12")
        self.label_20 = QtWidgets.QLabel(self.widget_4)
        self.label_20.setGeometry(QtCore.QRect(20, 150, 41, 16))
        self.label_20.setObjectName("label_20")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 91, 20))
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setGeometry(QtCore.QRect(20, 210, 191, 16))
        self.label_14.setObjectName("label_14")
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        self.label_11.setGeometry(QtCore.QRect(50, 120, 91, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(210, 210, 113, 23))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(310, 150, 113, 23))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.comboBox = QtWidgets.QComboBox(self.widget_4)
        self.comboBox.setGeometry(QtCore.QRect(110, 70, 79, 23))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setGeometry(QtCore.QRect(310, 120, 91, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(180, 150, 113, 23))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(50, 150, 113, 23))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setGeometry(QtCore.QRect(720, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_45 = QtWidgets.QLabel(self.widget_4)
        self.label_45.setGeometry(QtCore.QRect(210, 70, 91, 20))
        self.label_45.setObjectName("label_45")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_4.setGeometry(QtCore.QRect(290, 70, 79, 23))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_22 = QtWidgets.QLabel(self.widget_4)
        self.label_22.setGeometry(QtCore.QRect(450, 70, 131, 21))
        self.label_22.setObjectName("label_22")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(590, 70, 81, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_32 = QtWidgets.QLabel(self.widget_4)
        self.label_32.setGeometry(QtCore.QRect(450, 120, 151, 16))
        self.label_32.setObjectName("label_32")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_24.setGeometry(QtCore.QRect(590, 120, 81, 21))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.textEdit = QtWidgets.QTextEdit(self.widget_4)
        self.textEdit.setGeometry(QtCore.QRect(450, 200, 401, 91))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setGeometry(QtCore.QRect(720, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setGeometry(QtCore.QRect(720, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 10, 80, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 10, 80, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.widget_4, 1, 0, 1, 1)
        self.widget = MplWidget(self.X_Plane)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = MplWidget(self.X_Plane)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.X_Plane)
        self.widget_5.setObjectName("widget_5")
        self.layoutWidget = QtWidgets.QWidget(self.widget_5)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 269))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 5)
        self.gridLayout_3.setVerticalSpacing(12)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 3, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_3.addWidget(self.lineEdit_14, 5, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 5, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_3.addWidget(self.lineEdit_15, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 6, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 1, 1, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_3.addWidget(self.lineEdit_13, 4, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 1, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 2, 2, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_3.addWidget(self.lineEdit_20, 3, 2, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_3.addWidget(self.lineEdit_19, 4, 2, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_3.addWidget(self.lineEdit_18, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_3.addWidget(self.lineEdit_16, 6, 1, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 2)
        self.gridLayout_3.setColumnStretch(2, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 30, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setGeometry(QtCore.QRect(640, 80, 221, 41))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.widget_5, 1, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.X_Plane)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2.addWidget(self.widget_3, 0, 2, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.X_Plane)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_2.addWidget(self.widget_6, 1, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setRowStretch(0, 2)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.X_Plane, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1751, 851))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_8 = MplWidget(self.layoutWidget_2)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_4.addWidget(self.widget_8, 0, 0, 1, 1)
        self.widget_9 = MplWidget(self.layoutWidget_2)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_4.addWidget(self.widget_9, 0, 1, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.layoutWidget_2)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_4.addWidget(self.widget_11, 0, 2, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.layoutWidget_2)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_4.addWidget(self.widget_12, 1, 2, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.layoutWidget_2)
        self.widget_10.setObjectName("widget_10")
        self.widget_7 = QtWidgets.QWidget(self.widget_10)
        self.widget_7.setGeometry(QtCore.QRect(10, 10, 866, 279))
        self.widget_7.setObjectName("widget_7")
        self.layoutWidget_4 = QtWidgets.QWidget(self.widget_7)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 0, 771, 269))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 5)
        self.gridLayout_6.setVerticalSpacing(12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_6.addWidget(self.lineEdit_35, 3, 1, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_6.addWidget(self.lineEdit_36, 5, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 1, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 3, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_41.setObjectName("label_41")
        self.gridLayout_6.addWidget(self.label_41, 4, 0, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_37.setText("")
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_6.addWidget(self.lineEdit_37, 6, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 2, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 5, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_6.addWidget(self.lineEdit_38, 2, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_47.setObjectName("label_47")
        self.gridLayout_6.addWidget(self.label_47, 6, 0, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_6.addWidget(self.lineEdit_39, 1, 1, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_6.addWidget(self.lineEdit_40, 4, 1, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_6.addWidget(self.lineEdit_41, 1, 2, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_6.addWidget(self.lineEdit_42, 2, 2, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_6.addWidget(self.lineEdit_43, 3, 2, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_6.addWidget(self.lineEdit_44, 4, 2, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout_6.addWidget(self.lineEdit_45, 5, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 2, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.gridLayout_6.setColumnStretch(2, 2)
        self.gridLayout_4.addWidget(self.widget_10, 1, 1, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.layoutWidget_2)
        self.widget_13.setObjectName("widget_13")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_2.setGeometry(QtCore.QRect(40, 70, 79, 23))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_3.setGeometry(QtCore.QRect(350, 70, 79, 23))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_4 = QtWidgets.QLabel(self.widget_13)
        self.label_4.setGeometry(QtCore.QRect(40, 50, 57, 15))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.widget_13)
        self.label_7.setGeometry(QtCore.QRect(350, 40, 101, 20))
        self.label_7.setObjectName("label_7")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget_13)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 110, 251, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 2, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 0, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_5.addWidget(self.lineEdit_6, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widget_13)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(350, 110, 251, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_50.setObjectName("label_50")
        self.gridLayout_7.addWidget(self.label_50, 2, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.gridLayout_7.addWidget(self.label_51, 0, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.gridLayout_7.addWidget(self.label_52, 1, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_7.addWidget(self.lineEdit_17, 0, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_7.addWidget(self.lineEdit_21, 1, 1, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_7.addWidget(self.lineEdit_22, 2, 1, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.widget_13)
        self.radioButton.setGeometry(QtCore.QRect(670, 30, 99, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_13)
        self.radioButton_2.setGeometry(QtCore.QRect(670, 60, 99, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_4.setGeometry(QtCore.QRect(670, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(self.widget_13)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.widget_13, 1, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 2)
        self.gridLayout_4.setColumnStretch(1, 2)
        self.gridLayout_4.setRowStretch(0, 2)
        self.gridLayout_4.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Emittance & Twiss measurement"))
        self.label_12.setText(_translate("Form", "To"))
        self.label_20.setText(_translate("Form", "K1"))
        self.label_10.setText(_translate("Form", "which quad:"))
        self.label_14.setText(_translate("Form", "How many samples per step:"))
        self.label_11.setText(_translate("Form", "From"))
        self.comboBox.setItemText(0, _translate("Form", "QL27"))
        self.comboBox.setItemText(1, _translate("Form", "QT01"))
        self.comboBox.setItemText(2, _translate("Form", "QT02"))
        self.comboBox.setItemText(3, _translate("Form", "QL15"))
        self.comboBox.setItemText(4, _translate("Form", "QL16"))
        self.label_13.setText(_translate("Form", "Steps"))
        self.label_9.setText(_translate("Form", "Scan Control"))
        self.pushButton.setText(_translate("Form", "start "))
        self.label_45.setText(_translate("Form", "which flag:"))
        self.comboBox_4.setItemText(0, _translate("Form", "PRF06"))
        self.comboBox_4.setItemText(1, _translate("Form", "PRF07"))
        self.comboBox_4.setItemText(2, _translate("Form", "PRF08"))
        self.comboBox_4.setItemText(3, _translate("Form", "PRF04"))
        self.label_22.setText(_translate("Form", "Energy@quad (MeV)"))
        self.label_32.setText(_translate("Form", "Sampling interval (s)"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">PAY ATTENTION:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">1) Start &quot;Beam Monitor&quot; and then choose the proper pixel region to get the right fitting results of sigx &amp; sigy.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">2) &quot;simply VM&quot; can simply the lattice to speed up. &quot;full VM&quot;  to recover the full lattice.</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "clear"))
        self.pushButton_5.setText(_translate("Form", "Stop"))
        self.pushButton_6.setText(_translate("Form", "simply VM"))
        self.pushButton_7.setText(_translate("Form", "full VM"))
        self.label_16.setText(_translate("Form", "ex (mm mrad)"))
        self.label_17.setText(_translate("Form", "beta (m)"))
        self.label_18.setText(_translate("Form", "alpha "))
        self.label_15.setText(_translate("Form", "Results"))
        self.label_21.setText(_translate("Form", "exn (mm mrad)"))
        self.label_19.setText(_translate("Form", "gamma (/m)"))
        self.label_23.setText(_translate("Form", "Fitting curve"))
        self.label.setText(_translate("Form", "Parabolic fitting"))
        self.label_2.setText(_translate("Form", "Least Squares"))
        self.pushButton_2.setText(_translate("Form", "Recalculate"))
        self.label_3.setText(_translate("Form", "Recalculate from scanResults.json"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.X_Plane), _translate("Form", "X-Plane"))
        self.label_39.setText(_translate("Form", "ey (mm mrad)"))
        self.label_40.setText(_translate("Form", "beta (m)"))
        self.label_41.setText(_translate("Form", "alpha "))
        self.label_42.setText(_translate("Form", "Results"))
        self.label_43.setText(_translate("Form", "eyn (mm mrad)"))
        self.label_44.setText(_translate("Form", "gamma (/m)"))
        self.label_47.setText(_translate("Form", "Fitting curve"))
        self.label_5.setText(_translate("Form", "Parabolic fitting"))
        self.label_6.setText(_translate("Form", "Least Squares"))
        self.comboBox_2.setItemText(0, _translate("Form", "CQ1"))
        self.comboBox_2.setItemText(1, _translate("Form", "CQ2"))
        self.comboBox_2.setItemText(2, _translate("Form", "CQ3"))
        self.comboBox_2.setItemText(3, _translate("Form", "CQ4"))
        self.comboBox_2.setItemText(4, _translate("Form", "MQ1"))
        self.comboBox_2.setItemText(5, _translate("Form", "MQ2"))
        self.comboBox_3.setItemText(0, _translate("Form", "CQ1"))
        self.comboBox_3.setItemText(1, _translate("Form", "CQ2"))
        self.comboBox_3.setItemText(2, _translate("Form", "CQ3"))
        self.comboBox_3.setItemText(3, _translate("Form", "CQ4"))
        self.comboBox_3.setItemText(4, _translate("Form", "MQ1"))
        self.comboBox_3.setItemText(5, _translate("Form", "MQ2"))
        self.label_4.setText(_translate("Form", "Twiss at"))
        self.label_7.setText(_translate("Form", "To get twiss at"))
        self.label_49.setText(_translate("Form", "gamma (/m)"))
        self.label_48.setText(_translate("Form", "beta (m)"))
        self.label_46.setText(_translate("Form", "alpha "))
        self.label_50.setText(_translate("Form", "gamma (/m)"))
        self.label_51.setText(_translate("Form", "beta (m)"))
        self.label_52.setText(_translate("Form", "alpha "))
        self.radioButton.setText(_translate("Form", "inverse?"))
        self.radioButton_2.setText(_translate("Form", "Y-Plane"))
        self.pushButton_4.setText(_translate("Form", "Calculate"))
        self.label_8.setText(_translate("Form", "Twiss-i => twiss-j calculation:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Y-Plane"))
from mplwidget import MplWidget
