# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1251, 868)
        MainWindow.setStyleSheet("/* 基础背景 */\n"
"QMainWindow, QWidget#centralwidget {\n"
"    background-color: #1e1e2e;\n"
"    color: #cdd6f4;\n"
"}\n"
"\n"
"/* 左侧控制面板 */\n"
"QFrame {\n"
"    background-color: #242437;\n"
"    border-right: 1px solid #45475a;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"/* 按钮统一：科技蓝方案 */\n"
"QPushButton {\n"
"    background-color: #3e5f7a;\n"
"    border: 1px solid #589bcf;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"     font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a7a9d;\n"
"}\n"
"\n"
"/* 输入框：琥珀色高亮（延续之前的风格） */\n"
"QLineEdit {\n"
"    background-color: #181825;\n"
"    border: 1px solid #fab387;\n"
"    border-radius: 3px;\n"
"    color: #f9e2af;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"/* 绘图控件容器（虽然绘图背景由 Matplotlib 控制，但边框可以统一） */\n"
"MplWidget {\n"
"    border: 1px solid #313244;\n"
"    background-color: #000000;\n"
"}\n"
"\n"
"/* 标签文字 */\n"
"QLabel {\n"
"    color: #bac2de;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: #cdd6f4; /* 未选中时的文字颜色 */\n"
"    font-weight: normal;\n"
"    spacing: 8px;   /* 文字与圆圈之间的间距 */\n"
"}\n"
"\n"
"/* 3. 修改指示器（圆圈）的样式 */\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #45475a;\n"
"    border-radius: 9px; /* 圆角半径为宽的一半，确保是圆形 */\n"
"    background-color: #313244;\n"
"}\n"
"\n"
"/* 4. 选中时的指示器样式 */\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #a6e3a1; /* 选中时内部填充为绿色 */\n"
"    border: 2px solid #cdd6f4;  /* 亮色边框 */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(16)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.start_1 = QtWidgets.QPushButton(self.frame_2)
        self.start_1.setObjectName("start_1")
        self.verticalLayout_8.addWidget(self.start_1)
        self.stop_1 = QtWidgets.QPushButton(self.frame_2)
        self.stop_1.setObjectName("stop_1")
        self.verticalLayout_8.addWidget(self.stop_1)
        self.hold_1 = QtWidgets.QRadioButton(self.frame_2)
        self.hold_1.setObjectName("hold_1")
        self.verticalLayout_8.addWidget(self.hold_1)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.QL_cxmin = QtWidgets.QLineEdit(self.frame_2)
        self.QL_cxmin.setObjectName("QL_cxmin")
        self.gridLayout.addWidget(self.QL_cxmin, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.QL_cxmax = QtWidgets.QLineEdit(self.frame_2)
        self.QL_cxmax.setObjectName("QL_cxmax")
        self.gridLayout.addWidget(self.QL_cxmax, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bPMSLabel = QtWidgets.QLabel(self.frame_2)
        self.bPMSLabel.setObjectName("bPMSLabel")
        self.gridLayout_2.addWidget(self.bPMSLabel, 0, 0, 1, 1)
        self.bPMSLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.bPMSLineEdit.setObjectName("bPMSLineEdit")
        self.gridLayout_2.addWidget(self.bPMSLineEdit, 0, 1, 1, 1)
        self.bPMELabel = QtWidgets.QLabel(self.frame_2)
        self.bPMELabel.setObjectName("bPMELabel")
        self.gridLayout_2.addWidget(self.bPMELabel, 1, 0, 1, 1)
        self.bPMELineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.bPMELineEdit.setObjectName("bPMELineEdit")
        self.gridLayout_2.addWidget(self.bPMELineEdit, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(16)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(16)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.start_2 = QtWidgets.QPushButton(self.frame_3)
        self.start_2.setObjectName("start_2")
        self.verticalLayout_10.addWidget(self.start_2)
        self.stop_2 = QtWidgets.QPushButton(self.frame_3)
        self.stop_2.setObjectName("stop_2")
        self.verticalLayout_10.addWidget(self.stop_2)
        self.hold_2 = QtWidgets.QRadioButton(self.frame_3)
        self.hold_2.setObjectName("hold_2")
        self.verticalLayout_10.addWidget(self.hold_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.QL_cymin = QtWidgets.QLineEdit(self.frame_3)
        self.QL_cymin.setText("")
        self.QL_cymin.setPlaceholderText("")
        self.QL_cymin.setObjectName("QL_cymin")
        self.gridLayout_3.addWidget(self.QL_cymin, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.QL_cymax = QtWidgets.QLineEdit(self.frame_3)
        self.QL_cymax.setText("")
        self.QL_cymax.setPlaceholderText("")
        self.QL_cymax.setObjectName("QL_cymax")
        self.gridLayout_3.addWidget(self.QL_cymax, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.bPMSLabel_2 = QtWidgets.QLabel(self.frame_3)
        self.bPMSLabel_2.setObjectName("bPMSLabel_2")
        self.gridLayout_4.addWidget(self.bPMSLabel_2, 0, 0, 1, 1)
        self.bPMSLineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.bPMSLineEdit_2.setObjectName("bPMSLineEdit_2")
        self.gridLayout_4.addWidget(self.bPMSLineEdit_2, 0, 1, 1, 1)
        self.bPMYLabel = QtWidgets.QLabel(self.frame_3)
        self.bPMYLabel.setObjectName("bPMYLabel")
        self.gridLayout_4.addWidget(self.bPMYLabel, 1, 0, 1, 1)
        self.bPMYLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.bPMYLineEdit.setObjectName("bPMYLineEdit")
        self.gridLayout_4.addWidget(self.bPMYLineEdit, 1, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphWidget_1 = MplWidget(self.centralwidget)
        self.graphWidget_1.setObjectName("graphWidget_1")
        self.verticalLayout_4.addWidget(self.graphWidget_1)
        self.graphWidget_2 = MplWidget(self.centralwidget)
        self.graphWidget_2.setObjectName("graphWidget_2")
        self.verticalLayout_4.addWidget(self.graphWidget_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Orbit Display"))
        self.start_1.setText(_translate("MainWindow", "start"))
        self.stop_1.setText(_translate("MainWindow", "stop"))
        self.hold_1.setText(_translate("MainWindow", "hold on"))
        self.label_5.setText(_translate("MainWindow", "ymin"))
        self.label_6.setText(_translate("MainWindow", "ymax"))
        self.bPMSLabel.setText(_translate("MainWindow", "BPM#s"))
        self.bPMELabel.setText(_translate("MainWindow", "BPM#e"))
        self.start_2.setText(_translate("MainWindow", "start"))
        self.stop_2.setText(_translate("MainWindow", "stop"))
        self.hold_2.setText(_translate("MainWindow", "hold on"))
        self.label_7.setText(_translate("MainWindow", "ymin"))
        self.label_8.setText(_translate("MainWindow", "ymax"))
        self.bPMSLabel_2.setText(_translate("MainWindow", "BPM#s"))
        self.bPMYLabel.setText(_translate("MainWindow", "BPM#e"))
from mplwidget import MplWidget
