# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1251, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 20, 121, 291))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(16)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.start_1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.start_1.setObjectName("start_1")
        self.verticalLayout_8.addWidget(self.start_1)
        self.stop_1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.stop_1.setObjectName("stop_1")
        self.verticalLayout_8.addWidget(self.stop_1)
        self.hold_1 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.hold_1.setObjectName("hold_1")
        self.verticalLayout_8.addWidget(self.hold_1)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.QL_cxmin = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.QL_cxmin.setObjectName("QL_cxmin")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.QL_cxmin)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.QL_cxmax = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.QL_cxmax.setObjectName("QL_cxmax")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.QL_cxmax)
        self.verticalLayout_7.addLayout(self.formLayout_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.bPMSLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.bPMSLabel.setObjectName("bPMSLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bPMSLabel)
        self.bPMSLineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.bPMSLineEdit.setObjectName("bPMSLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bPMSLineEdit)
        self.bPMELabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.bPMELabel.setObjectName("bPMELabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bPMELabel)
        self.bPMELineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.bPMELineEdit.setObjectName("bPMELineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bPMELineEdit)
        self.verticalLayout_7.addLayout(self.formLayout_2)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.detail = QtWidgets.QPushButton(self.centralwidget)
        self.detail.setObjectName("detail")
        self.verticalLayout_6.addWidget(self.detail)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 20, 121, 291))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(16)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(16)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.start_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.start_2.setObjectName("start_2")
        self.verticalLayout_10.addWidget(self.start_2)
        self.stop_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.stop_2.setObjectName("stop_2")
        self.verticalLayout_10.addWidget(self.stop_2)
        self.hold_2 = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.hold_2.setObjectName("hold_2")
        self.verticalLayout_10.addWidget(self.hold_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.QL_cymin = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.QL_cymin.setText("")
        self.QL_cymin.setPlaceholderText("")
        self.QL_cymin.setObjectName("QL_cymin")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.QL_cymin)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.QL_cymax = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.QL_cymax.setText("")
        self.QL_cymax.setPlaceholderText("")
        self.QL_cymax.setObjectName("QL_cymax")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.QL_cymax)
        self.verticalLayout_9.addLayout(self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.bPMSLabel_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.bPMSLabel_2.setObjectName("bPMSLabel_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bPMSLabel_2)
        self.bPMSLineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.bPMSLineEdit_2.setObjectName("bPMSLineEdit_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bPMSLineEdit_2)
        self.bPMYLabel = QtWidgets.QLabel(self.layoutWidget_3)
        self.bPMYLabel.setObjectName("bPMYLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bPMYLabel)
        self.bPMYLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.bPMYLineEdit.setObjectName("bPMYLineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bPMYLineEdit)
        self.verticalLayout_9.addLayout(self.formLayout_5)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(20, 320, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.frame_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphWidget_1 = MplWidget(self.centralwidget)
        self.graphWidget_1.setObjectName("graphWidget_1")
        self.verticalLayout_4.addWidget(self.graphWidget_1)
        self.graphWidget_2 = MplWidget(self.centralwidget)
        self.graphWidget_2.setObjectName("graphWidget_2")
        self.verticalLayout_4.addWidget(self.graphWidget_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Orbit Display"))
        self.start_1.setText(_translate("MainWindow", "start"))
        self.stop_1.setText(_translate("MainWindow", "stop"))
        self.hold_1.setText(_translate("MainWindow", "hold on"))
        self.label_5.setText(_translate("MainWindow", "ymin"))
        self.label_6.setText(_translate("MainWindow", "ymax"))
        self.bPMSLabel.setText(_translate("MainWindow", "BPM#s"))
        self.bPMELabel.setText(_translate("MainWindow", "BPM#e"))
        self.detail.setText(_translate("MainWindow", "detail"))
        self.start_2.setText(_translate("MainWindow", "start"))
        self.stop_2.setText(_translate("MainWindow", "stop"))
        self.hold_2.setText(_translate("MainWindow", "hold on"))
        self.label_7.setText(_translate("MainWindow", "ymin"))
        self.label_8.setText(_translate("MainWindow", "ymax"))
        self.bPMSLabel_2.setText(_translate("MainWindow", "BPM#s"))
        self.bPMYLabel.setText(_translate("MainWindow", "BPM#e"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
from mplwidget import MplWidget
