# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subgui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(804, 765)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 741, 731))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.bPMx01Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx01Label.setObjectName("bPMx01Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bPMx01Label)
        self.bPMx01LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx01LineEdit.setReadOnly(True)
        self.bPMx01LineEdit.setObjectName("bPMx01LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bPMx01LineEdit)
        self.bPMx02Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx02Label.setObjectName("bPMx02Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bPMx02Label)
        self.bPMx02LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx02LineEdit.setReadOnly(True)
        self.bPMx02LineEdit.setObjectName("bPMx02LineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bPMx02LineEdit)
        self.bPMx03Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx03Label.setObjectName("bPMx03Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bPMx03Label)
        self.bPMx03LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx03LineEdit.setReadOnly(True)
        self.bPMx03LineEdit.setObjectName("bPMx03LineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bPMx03LineEdit)
        self.bPMx04Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx04Label.setObjectName("bPMx04Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bPMx04Label)
        self.bPMx04LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx04LineEdit.setReadOnly(True)
        self.bPMx04LineEdit.setObjectName("bPMx04LineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bPMx04LineEdit)
        self.bPMx05Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx05Label.setObjectName("bPMx05Label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.bPMx05Label)
        self.bPMx05LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx05LineEdit.setReadOnly(True)
        self.bPMx05LineEdit.setObjectName("bPMx05LineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bPMx05LineEdit)
        self.bPMx06Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx06Label.setObjectName("bPMx06Label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.bPMx06Label)
        self.bPMx06LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx06LineEdit.setReadOnly(True)
        self.bPMx06LineEdit.setObjectName("bPMx06LineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bPMx06LineEdit)
        self.bPMx07Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx07Label.setObjectName("bPMx07Label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.bPMx07Label)
        self.bPMx07LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx07LineEdit.setReadOnly(True)
        self.bPMx07LineEdit.setObjectName("bPMx07LineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.bPMx07LineEdit)
        self.bPMx08Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx08Label.setObjectName("bPMx08Label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.bPMx08Label)
        self.bPMx08LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx08LineEdit.setReadOnly(True)
        self.bPMx08LineEdit.setObjectName("bPMx08LineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.bPMx08LineEdit)
        self.bPMx09Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx09Label.setObjectName("bPMx09Label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.bPMx09Label)
        self.bPMx09LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx09LineEdit.setReadOnly(True)
        self.bPMx09LineEdit.setObjectName("bPMx09LineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.bPMx09LineEdit)
        self.bPMx10Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx10Label.setObjectName("bPMx10Label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bPMx10Label)
        self.bPMx10LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx10LineEdit.setReadOnly(True)
        self.bPMx10LineEdit.setObjectName("bPMx10LineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.bPMx10LineEdit)
        self.bPMx11Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx11Label.setObjectName("bPMx11Label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.bPMx11Label)
        self.bPMx11LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx11LineEdit.setReadOnly(True)
        self.bPMx11LineEdit.setObjectName("bPMx11LineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.bPMx11LineEdit)
        self.bPMx12Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx12Label.setObjectName("bPMx12Label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.bPMx12Label)
        self.bPMx12LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx12LineEdit.setReadOnly(True)
        self.bPMx12LineEdit.setObjectName("bPMx12LineEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.bPMx12LineEdit)
        self.bPMx13Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx13Label.setObjectName("bPMx13Label")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.bPMx13Label)
        self.bPMx13LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx13LineEdit.setReadOnly(True)
        self.bPMx13LineEdit.setObjectName("bPMx13LineEdit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.bPMx13LineEdit)
        self.bPMx14Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx14Label.setObjectName("bPMx14Label")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.bPMx14Label)
        self.bPMx14LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx14LineEdit.setReadOnly(True)
        self.bPMx14LineEdit.setObjectName("bPMx14LineEdit")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.bPMx14LineEdit)
        self.bPMx15Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx15Label.setObjectName("bPMx15Label")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.bPMx15Label)
        self.bPMx15LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx15LineEdit.setReadOnly(True)
        self.bPMx15LineEdit.setObjectName("bPMx15LineEdit")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.bPMx15LineEdit)
        self.bPMx16Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx16Label.setObjectName("bPMx16Label")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.bPMx16Label)
        self.bPMx16LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx16LineEdit.setReadOnly(True)
        self.bPMx16LineEdit.setObjectName("bPMx16LineEdit")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.bPMx16LineEdit)
        self.bPMx17Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx17Label.setObjectName("bPMx17Label")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.bPMx17Label)
        self.bPMx17LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx17LineEdit.setReadOnly(True)
        self.bPMx17LineEdit.setObjectName("bPMx17LineEdit")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.bPMx17LineEdit)
        self.bPMx18Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx18Label.setObjectName("bPMx18Label")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.bPMx18Label)
        self.bPMx18LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx18LineEdit.setReadOnly(True)
        self.bPMx18LineEdit.setObjectName("bPMx18LineEdit")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.bPMx18LineEdit)
        self.bPMx19Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx19Label.setObjectName("bPMx19Label")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.bPMx19Label)
        self.bPMx19LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx19LineEdit.setReadOnly(True)
        self.bPMx19LineEdit.setObjectName("bPMx19LineEdit")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.bPMx19LineEdit)
        self.bPMx20Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx20Label.setObjectName("bPMx20Label")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.bPMx20Label)
        self.bPMx20LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx20LineEdit.setReadOnly(True)
        self.bPMx20LineEdit.setObjectName("bPMx20LineEdit")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.bPMx20LineEdit)
        self.bPMx21Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx21Label.setObjectName("bPMx21Label")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.bPMx21Label)
        self.bPMx21LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx21LineEdit.setReadOnly(True)
        self.bPMx21LineEdit.setObjectName("bPMx21LineEdit")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.bPMx21LineEdit)
        self.bPMx22Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx22Label.setObjectName("bPMx22Label")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.bPMx22Label)
        self.bPMx22LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx22LineEdit.setReadOnly(True)
        self.bPMx22LineEdit.setObjectName("bPMx22LineEdit")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.bPMx22LineEdit)
        self.bPMx23Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx23Label.setObjectName("bPMx23Label")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.bPMx23Label)
        self.bPMx23LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx23LineEdit.setReadOnly(True)
        self.bPMx23LineEdit.setObjectName("bPMx23LineEdit")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.bPMx23LineEdit)
        self.bPMx24Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx24Label.setObjectName("bPMx24Label")
        self.formLayout.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.bPMx24Label)
        self.bPMx24LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx24LineEdit.setReadOnly(True)
        self.bPMx24LineEdit.setObjectName("bPMx24LineEdit")
        self.formLayout.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.bPMx24LineEdit)
        self.bPMx25Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx25Label.setObjectName("bPMx25Label")
        self.formLayout.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.bPMx25Label)
        self.bPMx25LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx25LineEdit.setReadOnly(True)
        self.bPMx25LineEdit.setObjectName("bPMx25LineEdit")
        self.formLayout.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.bPMx25LineEdit)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.bPMy01Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy01Label.setObjectName("bPMy01Label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bPMy01Label)
        self.bPMy01LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy01LineEdit.setReadOnly(True)
        self.bPMy01LineEdit.setObjectName("bPMy01LineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bPMy01LineEdit)
        self.bPMy02Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy02Label.setObjectName("bPMy02Label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bPMy02Label)
        self.bPMy02LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy02LineEdit.setReadOnly(True)
        self.bPMy02LineEdit.setObjectName("bPMy02LineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bPMy02LineEdit)
        self.bPMy03Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy03Label.setObjectName("bPMy03Label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bPMy03Label)
        self.bPMy03LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy03LineEdit.setReadOnly(True)
        self.bPMy03LineEdit.setObjectName("bPMy03LineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bPMy03LineEdit)
        self.bPMy04Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy04Label.setObjectName("bPMy04Label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bPMy04Label)
        self.bPMy04LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy04LineEdit.setReadOnly(True)
        self.bPMy04LineEdit.setObjectName("bPMy04LineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bPMy04LineEdit)
        self.bPMy05Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy05Label.setObjectName("bPMy05Label")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.bPMy05Label)
        self.bPMy05LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy05LineEdit.setReadOnly(True)
        self.bPMy05LineEdit.setObjectName("bPMy05LineEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bPMy05LineEdit)
        self.bPMy06Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy06Label.setObjectName("bPMy06Label")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.bPMy06Label)
        self.bPMy06LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy06LineEdit.setReadOnly(True)
        self.bPMy06LineEdit.setObjectName("bPMy06LineEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bPMy06LineEdit)
        self.bPMy07Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy07Label.setObjectName("bPMy07Label")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.bPMy07Label)
        self.bPMy07LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy07LineEdit.setReadOnly(True)
        self.bPMy07LineEdit.setObjectName("bPMy07LineEdit")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.bPMy07LineEdit)
        self.bPMy08Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy08Label.setObjectName("bPMy08Label")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.bPMy08Label)
        self.bPMy08LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy08LineEdit.setReadOnly(True)
        self.bPMy08LineEdit.setObjectName("bPMy08LineEdit")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.bPMy08LineEdit)
        self.bPMy09Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy09Label.setObjectName("bPMy09Label")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.bPMy09Label)
        self.bPMy09LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy09LineEdit.setReadOnly(True)
        self.bPMy09LineEdit.setObjectName("bPMy09LineEdit")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.bPMy09LineEdit)
        self.bPMy10Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy10Label.setObjectName("bPMy10Label")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bPMy10Label)
        self.bPMy10LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy10LineEdit.setReadOnly(True)
        self.bPMy10LineEdit.setObjectName("bPMy10LineEdit")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.bPMy10LineEdit)
        self.bPMy11Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy11Label.setObjectName("bPMy11Label")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.bPMy11Label)
        self.bPMy11LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy11LineEdit.setReadOnly(True)
        self.bPMy11LineEdit.setObjectName("bPMy11LineEdit")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.bPMy11LineEdit)
        self.bPMy12Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy12Label.setObjectName("bPMy12Label")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.bPMy12Label)
        self.bPMy12LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy12LineEdit.setReadOnly(True)
        self.bPMy12LineEdit.setObjectName("bPMy12LineEdit")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.bPMy12LineEdit)
        self.bPMy13Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy13Label.setObjectName("bPMy13Label")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.bPMy13Label)
        self.bPMy13LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy13LineEdit.setReadOnly(True)
        self.bPMy13LineEdit.setObjectName("bPMy13LineEdit")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.bPMy13LineEdit)
        self.bPMy14Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy14Label.setObjectName("bPMy14Label")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.bPMy14Label)
        self.bPMy14LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy14LineEdit.setReadOnly(True)
        self.bPMy14LineEdit.setObjectName("bPMy14LineEdit")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.bPMy14LineEdit)
        self.bPMy15Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy15Label.setObjectName("bPMy15Label")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.bPMy15Label)
        self.bPMy15LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy15LineEdit.setReadOnly(True)
        self.bPMy15LineEdit.setObjectName("bPMy15LineEdit")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.bPMy15LineEdit)
        self.bPMy16Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy16Label.setObjectName("bPMy16Label")
        self.formLayout_3.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.bPMy16Label)
        self.bPMy16LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy16LineEdit.setReadOnly(True)
        self.bPMy16LineEdit.setObjectName("bPMy16LineEdit")
        self.formLayout_3.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.bPMy16LineEdit)
        self.bPMy17Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy17Label.setObjectName("bPMy17Label")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.bPMy17Label)
        self.bPMy17LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy17LineEdit.setReadOnly(True)
        self.bPMy17LineEdit.setObjectName("bPMy17LineEdit")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.bPMy17LineEdit)
        self.bPMy18Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy18Label.setObjectName("bPMy18Label")
        self.formLayout_3.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.bPMy18Label)
        self.bPMy18LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy18LineEdit.setReadOnly(True)
        self.bPMy18LineEdit.setObjectName("bPMy18LineEdit")
        self.formLayout_3.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.bPMy18LineEdit)
        self.bPMy19Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy19Label.setObjectName("bPMy19Label")
        self.formLayout_3.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.bPMy19Label)
        self.bPMy19LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy19LineEdit.setReadOnly(True)
        self.bPMy19LineEdit.setObjectName("bPMy19LineEdit")
        self.formLayout_3.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.bPMy19LineEdit)
        self.bPMy20Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy20Label.setObjectName("bPMy20Label")
        self.formLayout_3.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.bPMy20Label)
        self.bPMy20LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy20LineEdit.setReadOnly(True)
        self.bPMy20LineEdit.setObjectName("bPMy20LineEdit")
        self.formLayout_3.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.bPMy20LineEdit)
        self.bPMy21Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy21Label.setObjectName("bPMy21Label")
        self.formLayout_3.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.bPMy21Label)
        self.bPMy21LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy21LineEdit.setReadOnly(True)
        self.bPMy21LineEdit.setObjectName("bPMy21LineEdit")
        self.formLayout_3.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.bPMy21LineEdit)
        self.bPMy22Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy22Label.setObjectName("bPMy22Label")
        self.formLayout_3.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.bPMy22Label)
        self.bPMy22LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy22LineEdit.setReadOnly(True)
        self.bPMy22LineEdit.setObjectName("bPMy22LineEdit")
        self.formLayout_3.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.bPMy22LineEdit)
        self.bPMy23Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy23Label.setObjectName("bPMy23Label")
        self.formLayout_3.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.bPMy23Label)
        self.bPMy23LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy23LineEdit.setReadOnly(True)
        self.bPMy23LineEdit.setObjectName("bPMy23LineEdit")
        self.formLayout_3.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.bPMy23LineEdit)
        self.bPMy24Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy24Label.setObjectName("bPMy24Label")
        self.formLayout_3.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.bPMy24Label)
        self.bPMy24LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy24LineEdit.setReadOnly(True)
        self.bPMy24LineEdit.setObjectName("bPMy24LineEdit")
        self.formLayout_3.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.bPMy24LineEdit)
        self.bPMy25Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy25Label.setObjectName("bPMy25Label")
        self.formLayout_3.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.bPMy25Label)
        self.bPMy25LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy25LineEdit.setReadOnly(True)
        self.bPMy25LineEdit.setObjectName("bPMy25LineEdit")
        self.formLayout_3.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.bPMy25LineEdit)
        self.horizontalLayout.addLayout(self.formLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.bPMx26Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx26Label.setObjectName("bPMx26Label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bPMx26Label)
        self.bPMx26LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx26LineEdit.setReadOnly(True)
        self.bPMx26LineEdit.setObjectName("bPMx26LineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bPMx26LineEdit)
        self.bPMx27Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx27Label.setObjectName("bPMx27Label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bPMx27Label)
        self.bPMx27LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx27LineEdit.setReadOnly(True)
        self.bPMx27LineEdit.setObjectName("bPMx27LineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bPMx27LineEdit)
        self.bPMx28Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx28Label.setObjectName("bPMx28Label")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bPMx28Label)
        self.bPMx28LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx28LineEdit.setReadOnly(True)
        self.bPMx28LineEdit.setObjectName("bPMx28LineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bPMx28LineEdit)
        self.bPMx29Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx29Label.setObjectName("bPMx29Label")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bPMx29Label)
        self.bPMx29LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx29LineEdit.setReadOnly(True)
        self.bPMx29LineEdit.setObjectName("bPMx29LineEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bPMx29LineEdit)
        self.bPMx30Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx30Label.setObjectName("bPMx30Label")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.bPMx30Label)
        self.bPMx30LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx30LineEdit.setReadOnly(True)
        self.bPMx30LineEdit.setObjectName("bPMx30LineEdit")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bPMx30LineEdit)
        self.bPMx31Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx31Label.setObjectName("bPMx31Label")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.bPMx31Label)
        self.bPMx31LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx31LineEdit.setReadOnly(True)
        self.bPMx31LineEdit.setObjectName("bPMx31LineEdit")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bPMx31LineEdit)
        self.bPMx32Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx32Label.setObjectName("bPMx32Label")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.bPMx32Label)
        self.bPMx32LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx32LineEdit.setReadOnly(True)
        self.bPMx32LineEdit.setObjectName("bPMx32LineEdit")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.bPMx32LineEdit)
        self.bPMx33Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx33Label.setObjectName("bPMx33Label")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.bPMx33Label)
        self.bPMx33LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx33LineEdit.setReadOnly(True)
        self.bPMx33LineEdit.setObjectName("bPMx33LineEdit")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.bPMx33LineEdit)
        self.bPMx34Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx34Label.setObjectName("bPMx34Label")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.bPMx34Label)
        self.bPMx34LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx34LineEdit.setReadOnly(True)
        self.bPMx34LineEdit.setObjectName("bPMx34LineEdit")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.bPMx34LineEdit)
        self.bPMx35Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx35Label.setObjectName("bPMx35Label")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bPMx35Label)
        self.bPMx35LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx35LineEdit.setReadOnly(True)
        self.bPMx35LineEdit.setObjectName("bPMx35LineEdit")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.bPMx35LineEdit)
        self.bPMx36Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx36Label.setObjectName("bPMx36Label")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.bPMx36Label)
        self.bPMx36LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx36LineEdit.setReadOnly(True)
        self.bPMx36LineEdit.setObjectName("bPMx36LineEdit")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.bPMx36LineEdit)
        self.bPMx37Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx37Label.setObjectName("bPMx37Label")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.bPMx37Label)
        self.bPMx37LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx37LineEdit.setReadOnly(True)
        self.bPMx37LineEdit.setObjectName("bPMx37LineEdit")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.bPMx37LineEdit)
        self.bPMx38Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx38Label.setObjectName("bPMx38Label")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.bPMx38Label)
        self.bPMx38LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx38LineEdit.setReadOnly(True)
        self.bPMx38LineEdit.setObjectName("bPMx38LineEdit")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.bPMx38LineEdit)
        self.bPMx39Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx39Label.setObjectName("bPMx39Label")
        self.formLayout_4.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.bPMx39Label)
        self.bPMx39LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx39LineEdit.setReadOnly(True)
        self.bPMx39LineEdit.setObjectName("bPMx39LineEdit")
        self.formLayout_4.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.bPMx39LineEdit)
        self.bPMx40Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx40Label.setObjectName("bPMx40Label")
        self.formLayout_4.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.bPMx40Label)
        self.bPMx40LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx40LineEdit.setReadOnly(True)
        self.bPMx40LineEdit.setObjectName("bPMx40LineEdit")
        self.formLayout_4.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.bPMx40LineEdit)
        self.bPMx41Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx41Label.setObjectName("bPMx41Label")
        self.formLayout_4.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.bPMx41Label)
        self.bPMx41LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx41LineEdit.setReadOnly(True)
        self.bPMx41LineEdit.setObjectName("bPMx41LineEdit")
        self.formLayout_4.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.bPMx41LineEdit)
        self.bPMx42Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx42Label.setObjectName("bPMx42Label")
        self.formLayout_4.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.bPMx42Label)
        self.bPMx42LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx42LineEdit.setReadOnly(True)
        self.bPMx42LineEdit.setObjectName("bPMx42LineEdit")
        self.formLayout_4.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.bPMx42LineEdit)
        self.bPMx43Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMx43Label.setObjectName("bPMx43Label")
        self.formLayout_4.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.bPMx43Label)
        self.bPMx43LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMx43LineEdit.setReadOnly(True)
        self.bPMx43LineEdit.setObjectName("bPMx43LineEdit")
        self.formLayout_4.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.bPMx43LineEdit)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setObjectName("formLayout_11")
        self.bPMy26Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy26Label.setObjectName("bPMy26Label")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.bPMy26Label)
        self.bPMy26LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy26LineEdit.setReadOnly(True)
        self.bPMy26LineEdit.setObjectName("bPMy26LineEdit")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bPMy26LineEdit)
        self.bPMy27Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy27Label.setObjectName("bPMy27Label")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bPMy27Label)
        self.bPMy27LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy27LineEdit.setReadOnly(True)
        self.bPMy27LineEdit.setObjectName("bPMy27LineEdit")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bPMy27LineEdit)
        self.bPMy28Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy28Label.setObjectName("bPMy28Label")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bPMy28Label)
        self.bPMy28LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy28LineEdit.setReadOnly(True)
        self.bPMy28LineEdit.setObjectName("bPMy28LineEdit")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bPMy28LineEdit)
        self.bPMy29Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy29Label.setObjectName("bPMy29Label")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bPMy29Label)
        self.bPMy29LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy29LineEdit.setReadOnly(True)
        self.bPMy29LineEdit.setObjectName("bPMy29LineEdit")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bPMy29LineEdit)
        self.bPMy30Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy30Label.setObjectName("bPMy30Label")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.bPMy30Label)
        self.bPMy30LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy30LineEdit.setReadOnly(True)
        self.bPMy30LineEdit.setObjectName("bPMy30LineEdit")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bPMy30LineEdit)
        self.bPMy31Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy31Label.setObjectName("bPMy31Label")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.bPMy31Label)
        self.bPMy31LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy31LineEdit.setReadOnly(True)
        self.bPMy31LineEdit.setObjectName("bPMy31LineEdit")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bPMy31LineEdit)
        self.bPMy32Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy32Label.setObjectName("bPMy32Label")
        self.formLayout_11.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.bPMy32Label)
        self.bPMy32LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy32LineEdit.setReadOnly(True)
        self.bPMy32LineEdit.setObjectName("bPMy32LineEdit")
        self.formLayout_11.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.bPMy32LineEdit)
        self.bPMy33Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy33Label.setObjectName("bPMy33Label")
        self.formLayout_11.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.bPMy33Label)
        self.bPMy33LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy33LineEdit.setReadOnly(True)
        self.bPMy33LineEdit.setObjectName("bPMy33LineEdit")
        self.formLayout_11.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.bPMy33LineEdit)
        self.bPMy34Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy34Label.setObjectName("bPMy34Label")
        self.formLayout_11.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.bPMy34Label)
        self.bPMy34LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy34LineEdit.setReadOnly(True)
        self.bPMy34LineEdit.setObjectName("bPMy34LineEdit")
        self.formLayout_11.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.bPMy34LineEdit)
        self.bPMy35Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy35Label.setObjectName("bPMy35Label")
        self.formLayout_11.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.bPMy35Label)
        self.bPMy35LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy35LineEdit.setReadOnly(True)
        self.bPMy35LineEdit.setObjectName("bPMy35LineEdit")
        self.formLayout_11.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.bPMy35LineEdit)
        self.bPMy36Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy36Label.setObjectName("bPMy36Label")
        self.formLayout_11.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.bPMy36Label)
        self.bPMy36LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy36LineEdit.setReadOnly(True)
        self.bPMy36LineEdit.setObjectName("bPMy36LineEdit")
        self.formLayout_11.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.bPMy36LineEdit)
        self.bPMy37Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy37Label.setObjectName("bPMy37Label")
        self.formLayout_11.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.bPMy37Label)
        self.bPMy37LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy37LineEdit.setReadOnly(True)
        self.bPMy37LineEdit.setObjectName("bPMy37LineEdit")
        self.formLayout_11.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.bPMy37LineEdit)
        self.bPMy38Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy38Label.setObjectName("bPMy38Label")
        self.formLayout_11.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.bPMy38Label)
        self.bPMy38LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy38LineEdit.setReadOnly(True)
        self.bPMy38LineEdit.setObjectName("bPMy38LineEdit")
        self.formLayout_11.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.bPMy38LineEdit)
        self.bPMy39Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy39Label.setObjectName("bPMy39Label")
        self.formLayout_11.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.bPMy39Label)
        self.bPMy39LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy39LineEdit.setReadOnly(True)
        self.bPMy39LineEdit.setObjectName("bPMy39LineEdit")
        self.formLayout_11.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.bPMy39LineEdit)
        self.bPMy40Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy40Label.setObjectName("bPMy40Label")
        self.formLayout_11.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.bPMy40Label)
        self.bPMy40LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy40LineEdit.setReadOnly(True)
        self.bPMy40LineEdit.setObjectName("bPMy40LineEdit")
        self.formLayout_11.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.bPMy40LineEdit)
        self.bPMy41Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy41Label.setObjectName("bPMy41Label")
        self.formLayout_11.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.bPMy41Label)
        self.bPMy41LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy41LineEdit.setReadOnly(True)
        self.bPMy41LineEdit.setObjectName("bPMy41LineEdit")
        self.formLayout_11.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.bPMy41LineEdit)
        self.bPMy42Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy42Label.setObjectName("bPMy42Label")
        self.formLayout_11.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.bPMy42Label)
        self.bPMy42LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy42LineEdit.setReadOnly(True)
        self.bPMy42LineEdit.setObjectName("bPMy42LineEdit")
        self.formLayout_11.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.bPMy42LineEdit)
        self.bPMy43Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.bPMy43Label.setObjectName("bPMy43Label")
        self.formLayout_11.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.bPMy43Label)
        self.bPMy43LineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.bPMy43LineEdit.setReadOnly(True)
        self.bPMy43LineEdit.setObjectName("bPMy43LineEdit")
        self.formLayout_11.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.bPMy43LineEdit)
        self.horizontalLayout.addLayout(self.formLayout_11)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bPMx01Label.setText(_translate("Form", "BPMx01"))
        self.bPMx02Label.setText(_translate("Form", "BPMx02"))
        self.bPMx03Label.setText(_translate("Form", "BPMx03"))
        self.bPMx04Label.setText(_translate("Form", "BPMx04"))
        self.bPMx05Label.setText(_translate("Form", "BPMx05"))
        self.bPMx06Label.setText(_translate("Form", "BPMx06"))
        self.bPMx07Label.setText(_translate("Form", "BPMx07"))
        self.bPMx08Label.setText(_translate("Form", "BPMx08"))
        self.bPMx09Label.setText(_translate("Form", "BPMx09"))
        self.bPMx10Label.setText(_translate("Form", "BPMx10"))
        self.bPMx11Label.setText(_translate("Form", "BPMx11"))
        self.bPMx12Label.setText(_translate("Form", "BPMx12"))
        self.bPMx13Label.setText(_translate("Form", "BPMx13"))
        self.bPMx14Label.setText(_translate("Form", "BPMx14"))
        self.bPMx15Label.setText(_translate("Form", "BPMx15"))
        self.bPMx16Label.setText(_translate("Form", "BPMx16"))
        self.bPMx17Label.setText(_translate("Form", "BPMx17"))
        self.bPMx18Label.setText(_translate("Form", "BPMx18"))
        self.bPMx19Label.setText(_translate("Form", "BPMx19"))
        self.bPMx20Label.setText(_translate("Form", "BPMx20"))
        self.bPMx21Label.setText(_translate("Form", "BPMx21"))
        self.bPMx22Label.setText(_translate("Form", "BPMx22"))
        self.bPMx23Label.setText(_translate("Form", "BPMx23"))
        self.bPMx24Label.setText(_translate("Form", "BPMx24"))
        self.bPMx25Label.setText(_translate("Form", "BPMx25"))
        self.bPMy01Label.setText(_translate("Form", "BPMy01"))
        self.bPMy02Label.setText(_translate("Form", "BPMy02"))
        self.bPMy03Label.setText(_translate("Form", "BPMy03"))
        self.bPMy04Label.setText(_translate("Form", "BPMy04"))
        self.bPMy05Label.setText(_translate("Form", "BPMy05"))
        self.bPMy06Label.setText(_translate("Form", "BPMy06"))
        self.bPMy07Label.setText(_translate("Form", "BPMy07"))
        self.bPMy08Label.setText(_translate("Form", "BPMy08"))
        self.bPMy09Label.setText(_translate("Form", "BPMy09"))
        self.bPMy10Label.setText(_translate("Form", "BPMy10"))
        self.bPMy11Label.setText(_translate("Form", "BPMy11"))
        self.bPMy12Label.setText(_translate("Form", "BPMy12"))
        self.bPMy13Label.setText(_translate("Form", "BPMy13"))
        self.bPMy14Label.setText(_translate("Form", "BPMy14"))
        self.bPMy15Label.setText(_translate("Form", "BPMy15"))
        self.bPMy16Label.setText(_translate("Form", "BPMy16"))
        self.bPMy17Label.setText(_translate("Form", "BPMy17"))
        self.bPMy18Label.setText(_translate("Form", "BPMy18"))
        self.bPMy19Label.setText(_translate("Form", "BPMy19"))
        self.bPMy20Label.setText(_translate("Form", "BPMy20"))
        self.bPMy21Label.setText(_translate("Form", "BPMy21"))
        self.bPMy22Label.setText(_translate("Form", "BPMy22"))
        self.bPMy23Label.setText(_translate("Form", "BPMy23"))
        self.bPMy24Label.setText(_translate("Form", "BPMy24"))
        self.bPMy25Label.setText(_translate("Form", "BPMy25"))
        self.bPMx26Label.setText(_translate("Form", "BPMx26"))
        self.bPMx27Label.setText(_translate("Form", "BPMx27"))
        self.bPMx28Label.setText(_translate("Form", "BPMx28"))
        self.bPMx29Label.setText(_translate("Form", "BPMx29"))
        self.bPMx30Label.setText(_translate("Form", "BPMx30"))
        self.bPMx31Label.setText(_translate("Form", "BPMx31"))
        self.bPMx32Label.setText(_translate("Form", "BPMx32"))
        self.bPMx33Label.setText(_translate("Form", "BPMx33"))
        self.bPMx34Label.setText(_translate("Form", "BPMx34"))
        self.bPMx35Label.setText(_translate("Form", "BPMx35"))
        self.bPMx36Label.setText(_translate("Form", "BPMx36"))
        self.bPMx37Label.setText(_translate("Form", "BPMx37"))
        self.bPMx38Label.setText(_translate("Form", "BPMx38"))
        self.bPMx39Label.setText(_translate("Form", "BPMx39"))
        self.bPMx40Label.setText(_translate("Form", "BPMx40"))
        self.bPMx41Label.setText(_translate("Form", "BPMx41"))
        self.bPMx42Label.setText(_translate("Form", "BPMx42"))
        self.bPMx43Label.setText(_translate("Form", "BPMx43"))
        self.bPMy26Label.setText(_translate("Form", "BPMy26"))
        self.bPMy27Label.setText(_translate("Form", "BPMy27"))
        self.bPMy28Label.setText(_translate("Form", "BPMy28"))
        self.bPMy29Label.setText(_translate("Form", "BPMy29"))
        self.bPMy30Label.setText(_translate("Form", "BPMy30"))
        self.bPMy31Label.setText(_translate("Form", "BPMy31"))
        self.bPMy32Label.setText(_translate("Form", "BPMy32"))
        self.bPMy33Label.setText(_translate("Form", "BPMy33"))
        self.bPMy34Label.setText(_translate("Form", "BPMy34"))
        self.bPMy35Label.setText(_translate("Form", "BPMy35"))
        self.bPMy36Label.setText(_translate("Form", "BPMy36"))
        self.bPMy37Label.setText(_translate("Form", "BPMy37"))
        self.bPMy38Label.setText(_translate("Form", "BPMy38"))
        self.bPMy39Label.setText(_translate("Form", "BPMy39"))
        self.bPMy40Label.setText(_translate("Form", "BPMy40"))
        self.bPMy41Label.setText(_translate("Form", "BPMy41"))
        self.bPMy42Label.setText(_translate("Form", "BPMy42"))
        self.bPMy43Label.setText(_translate("Form", "BPMy43"))
