# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1604, 928)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = MplWidget(self.tab)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = MplWidget(self.tab)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2.addWidget(self.widget_2, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 140, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(260, 190, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(350, 190, 113, 23))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(200, 40, 113, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 40, 71, 16))
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(480, 40, 113, 23))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        self.comboBox_4.setGeometry(QtCore.QRect(240, 140, 79, 23))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(480, 10, 71, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 40, 113, 23))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 90, 113, 23))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(120, 190, 113, 23))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(100, 90, 79, 23))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(70, 140, 79, 23))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(200, 140, 71, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(480, 90, 113, 23))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(360, 10, 71, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(100, 40, 79, 23))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(340, 90, 113, 23))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 90, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(30, 190, 81, 16))
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 80, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(20, 160, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(260, 160, 161, 31))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 80, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_5.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_2.addWidget(self.frame_2, 1, 1, 1, 1)
        self.gridLayout_2.setRowStretch(0, 4)
        self.gridLayout_2.setRowStretch(1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_4 = MplWidget(self.tab_2)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3.addWidget(self.widget_4, 0, 1, 1, 1)
        self.widget_3 = MplWidget(self.tab_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3.addWidget(self.widget_3, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(550, 170, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(230, 10, 71, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(640, 170, 113, 23))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(200, 70, 113, 23))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(550, 70, 113, 23))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_6.setGeometry(QtCore.QRect(250, 120, 79, 23))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(550, 10, 71, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(370, 70, 113, 23))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(200, 30, 113, 23))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(420, 170, 113, 23))
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_7.setGeometry(QtCore.QRect(90, 30, 79, 23))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_8.setGeometry(QtCore.QRect(90, 120, 79, 23))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(180, 120, 71, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_16.setGeometry(QtCore.QRect(550, 30, 113, 23))
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(390, 10, 71, 16))
        self.label_17.setObjectName("label_17")
        self.comboBox_9 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_9.setGeometry(QtCore.QRect(90, 70, 79, 23))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_17.setGeometry(QtCore.QRect(370, 30, 113, 23))
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setGeometry(QtCore.QRect(330, 170, 81, 16))
        self.label_19.setObjectName("label_19")
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setGeometry(QtCore.QRect(20, 170, 161, 16))
        self.label_22.setObjectName("label_22")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_20.setGeometry(QtCore.QRect(180, 170, 113, 23))
        self.lineEdit_20.setText("")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_22.setGeometry(QtCore.QRect(480, 120, 113, 23))
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(370, 120, 111, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(20, 210, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(20, 250, 71, 16))
        self.label_26.setObjectName("label_26")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_23.setGeometry(QtCore.QRect(90, 250, 221, 21))
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(340, 250, 71, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_24.setGeometry(QtCore.QRect(410, 250, 221, 21))
        self.lineEdit_24.setText("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(20, 290, 71, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_25.setGeometry(QtCore.QRect(90, 290, 113, 23))
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_26.setGeometry(QtCore.QRect(410, 290, 113, 23))
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_29 = QtWidgets.QLabel(self.frame_3)
        self.label_29.setGeometry(QtCore.QRect(340, 290, 71, 16))
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 90, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setGeometry(QtCore.QRect(20, 260, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_18.setGeometry(QtCore.QRect(250, 260, 161, 31))
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(160, 90, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox_10 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_10.setGeometry(QtCore.QRect(20, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.label_21 = QtWidgets.QLabel(self.frame_4)
        self.label_21.setGeometry(QtCore.QRect(20, 210, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_19.setGeometry(QtCore.QRect(250, 210, 161, 31))
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_23 = QtWidgets.QLabel(self.frame_4)
        self.label_23.setGeometry(QtCore.QRect(20, 160, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_21.setGeometry(QtCore.QRect(250, 160, 161, 31))
        self.lineEdit_21.setText("")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(420, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox_11 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_11.setGeometry(QtCore.QRect(130, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_11.setFont(font)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout_3.addWidget(self.frame_4, 1, 1, 1, 1)
        self.gridLayout_3.setRowStretch(0, 5)
        self.gridLayout_3.setRowStretch(1, 3)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BBA"))
        self.label_6.setText(_translate("Form", "BPM1"))
        self.label_9.setText(_translate("Form", "Samples/step"))
        self.label_2.setText(_translate("Form", "From"))
        self.label.setText(_translate("Form", "Corrector"))
        self.comboBox_4.setItemText(0, _translate("Form", "BPM07"))
        self.comboBox_4.setItemText(1, _translate("Form", "BPM08"))
        self.comboBox_4.setItemText(2, _translate("Form", "BPM02"))
        self.comboBox_4.setItemText(3, _translate("Form", "BPM03"))
        self.label_4.setText(_translate("Form", "Steps"))
        self.comboBox_2.setItemText(0, _translate("Form", "CQ3"))
        self.comboBox_2.setItemText(1, _translate("Form", "CQ4"))
        self.comboBox_2.setItemText(2, _translate("Form", "MQ11"))
        self.comboBox_2.setItemText(3, _translate("Form", "MQ12"))
        self.comboBox_2.setItemText(4, _translate("Form", "CQ1"))
        self.comboBox_2.setItemText(5, _translate("Form", "CQ2"))
        self.comboBox_3.setItemText(0, _translate("Form", "BPM03"))
        self.comboBox_3.setItemText(1, _translate("Form", "BPM02"))
        self.comboBox_3.setItemText(2, _translate("Form", "BPM07"))
        self.label_7.setText(_translate("Form", "BPM2"))
        self.label_3.setText(_translate("Form", "To"))
        self.comboBox.setItemText(0, _translate("Form", "HC01"))
        self.comboBox.setItemText(1, _translate("Form", "VC01"))
        self.comboBox.setItemText(2, _translate("Form", "HC2"))
        self.comboBox.setItemText(3, _translate("Form", "VC2"))
        self.comboBox.setItemText(4, _translate("Form", "HC5"))
        self.comboBox.setItemText(5, _translate("Form", "VC5"))
        self.comboBox.setItemText(6, _translate("Form", "MS:HC"))
        self.comboBox.setItemText(7, _translate("Form", "MS:VC"))
        self.comboBox.setItemText(8, _translate("Form", "LS:HC"))
        self.comboBox.setItemText(9, _translate("Form", "LS:VC"))
        self.comboBox.setItemText(10, _translate("Form", "HIC01"))
        self.comboBox.setItemText(11, _translate("Form", "VIC01"))
        self.comboBox.setItemText(12, _translate("Form", "HIC02"))
        self.comboBox.setItemText(13, _translate("Form", "VIC02"))
        self.label_5.setText(_translate("Form", "Quad"))
        self.label_8.setText(_translate("Form", "Scan freq (s)"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.pushButton_4.setText(_translate("Form", "Stop"))
        self.label_13.setText(_translate("Form", "Offset of BPM1-Quad (mm)"))
        self.pushButton_3.setText(_translate("Form", "Recalculate"))
        self.pushButton_2.setText(_translate("Form", "Clear"))
        self.comboBox_5.setItemText(0, _translate("Form", "X-Plane"))
        self.comboBox_5.setItemText(1, _translate("Form", "Y-Plane"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "BBA-1"))
        self.label_10.setText(_translate("Form", "1st BPM"))
        self.label_11.setText(_translate("Form", "Samples/step"))
        self.label_12.setText(_translate("Form", "From"))
        self.label_14.setText(_translate("Form", "Corrector"))
        self.comboBox_6.setItemText(0, _translate("Form", "BPM21"))
        self.comboBox_6.setItemText(1, _translate("Form", "BPM28"))
        self.comboBox_6.setItemText(2, _translate("Form", "BPM29"))
        self.label_15.setText(_translate("Form", "Steps"))
        self.comboBox_7.setItemText(0, _translate("Form", "QT01"))
        self.comboBox_7.setItemText(1, _translate("Form", "QT18"))
        self.comboBox_8.setItemText(0, _translate("Form", "BPM20"))
        self.comboBox_8.setItemText(1, _translate("Form", "BPM27"))
        self.comboBox_8.setItemText(2, _translate("Form", "BPM28"))
        self.label_16.setText(_translate("Form", "2nd BPM"))
        self.label_17.setText(_translate("Form", "To"))
        self.comboBox_9.setItemText(0, _translate("Form", "XC21"))
        self.comboBox_9.setItemText(1, _translate("Form", "YC21"))
        self.comboBox_9.setItemText(2, _translate("Form", "XC29"))
        self.comboBox_9.setItemText(3, _translate("Form", "YC29"))
        self.label_18.setText(_translate("Form", "Quad"))
        self.label_19.setText(_translate("Form", "Scan freq (s)"))
        self.label_22.setText(_translate("Form", "Energy@corrector (MeV)"))
        self.label_24.setText(_translate("Form", "BPM1 samples #"))
        self.label_25.setText(_translate("Form", "Corrector model:"))
        self.label_26.setText(_translate("Form", "By (Gauss)"))
        self.label_27.setText(_translate("Form", "Bx (Gauss)"))
        self.label_28.setText(_translate("Form", "Leff (m)"))
        self.label_29.setText(_translate("Form", "Leff (m)"))
        self.pushButton_5.setText(_translate("Form", "Start"))
        self.pushButton_6.setText(_translate("Form", "Stop"))
        self.label_20.setText(_translate("Form", "Offset of BPM1-Quad (mm)"))
        self.pushButton_8.setText(_translate("Form", "Clear"))
        self.comboBox_10.setItemText(0, _translate("Form", "X-Plane"))
        self.comboBox_10.setItemText(1, _translate("Form", "Y-Plane"))
        self.label_21.setText(_translate("Form", "Response matrix R12 (m)"))
        self.label_23.setText(_translate("Form", "Average of BPM1 (mm)"))
        self.pushButton_7.setText(_translate("Form", "Recalculate"))
        self.comboBox_11.setItemText(0, _translate("Form", "Real Machine"))
        self.comboBox_11.setItemText(1, _translate("Form", "Virtual Machine"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "BBA-2"))
from mplwidget import MplWidget
