#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/common.sh"

MACHINE_ID="${HALF_LINAC_MACHINE_ID:-}"
EPICS_BASE_ARG=""

usage() {
  cat <<'EOF'
Usage: bash scripts/build_ioc.sh [--machine ID] [--epics-base PATH]

Rebuild one repository softIOC using a machine-local EPICS Base. If
--epics-base is omitted, EPICS_BASE, configure/RELEASE.local, and finally
configure/RELEASE are checked in that order.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --machine)
      MACHINE_ID="${2:-}"
      shift 2
      ;;
    --epics-base)
      EPICS_BASE_ARG="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

IOC_DIR="$(
  python3 -c 'import sys; from half_linac.src.shared.machine_profile import resolve_machine_runtime; print(resolve_machine_runtime(sys.argv[1] or None).softioc.root)' "$MACHINE_ID"
)"
RELEASE_FILE="$IOC_DIR/configure/RELEASE"
RELEASE_LOCAL_FILE="$IOC_DIR/configure/RELEASE.local"

read_release_var() {
  local file="$1"
  local name="$2"

  [[ -f "$file" ]] || return 0
  awk -F'=' -v name="$name" '
    $0 ~ "^[[:space:]]*" name "[[:space:]]*=" {
      sub(/^[[:space:]]*[^=]+=[[:space:]]*/, "", $0)
      sub(/[[:space:]]*#.*/, "", $0)
      gsub(/[[:space:]]+$/, "", $0)
      print
      exit
    }
  ' "$file"
}

EPICS_BASE_VALUE="$EPICS_BASE_ARG"
if [[ -z "$EPICS_BASE_VALUE" ]]; then
  EPICS_BASE_VALUE="${EPICS_BASE:-}"
fi
if [[ -z "$EPICS_BASE_VALUE" ]]; then
  EPICS_BASE_VALUE="$(read_release_var "$RELEASE_LOCAL_FILE" "EPICS_BASE")"
fi
if [[ -z "$EPICS_BASE_VALUE" ]]; then
  EPICS_BASE_VALUE="$(read_release_var "$RELEASE_FILE" "EPICS_BASE")"
fi
if [[ -z "$EPICS_BASE_VALUE" ]]; then
  echo "EPICS_BASE is not configured." >&2
  echo "Run: bash scripts/configure_softioc.sh --epics-base /path/to/epics-base" >&2
  exit 1
fi

EPICS_BASE_INPUT="$EPICS_BASE_VALUE"
EPICS_BASE_VALUE="$(cd "$EPICS_BASE_INPUT" 2>/dev/null && pwd)" || {
  echo "EPICS_BASE directory does not exist: $EPICS_BASE_INPUT" >&2
  exit 1
}

if [[ ! -f "$EPICS_BASE_VALUE/configure/CONFIG_BASE" ]]; then
  echo "EPICS_BASE does not point to a valid EPICS installation: $EPICS_BASE_VALUE" >&2
  exit 1
fi

export EPICS_BASE="$EPICS_BASE_VALUE"
if [[ -x "$EPICS_BASE/startup/EpicsHostArch" ]]; then
  export EPICS_HOST_ARCH="$("$EPICS_BASE/startup/EpicsHostArch")"
fi

{
  echo "# Generated by scripts/build_ioc.sh; do not commit."
  echo "EPICS_BASE = $EPICS_BASE_VALUE"
} > "$RELEASE_LOCAL_FILE"

echo "Rebuilding softIOC in $IOC_DIR"
echo "Using EPICS_BASE=$EPICS_BASE"

# EPICS requires EPICS_BASE to have make origin "file". Passing it on the
# command line makes CONFIG reject it, so RELEASE.local is the source of truth.
make -C "$IOC_DIR" rebuild

ENV_PATHS="$IOC_DIR/iocBoot/ioctarget/envPaths"
if [[ ! -f "$ENV_PATHS" ]] || ! grep -Fq "epicsEnvSet(\"TOP\",\"$IOC_DIR\")" "$ENV_PATHS"; then
  echo "IOC rebuild did not generate envPaths for the current checkout: $ENV_PATHS" >&2
  exit 1
fi
if ! grep -Fq "epicsEnvSet(\"EPICS_BASE\",\"$EPICS_BASE_VALUE\")" "$ENV_PATHS"; then
  echo "IOC rebuild did not record the selected EPICS_BASE in $ENV_PATHS" >&2
  exit 1
fi

HOST_ARCH="${EPICS_HOST_ARCH:-}"
if [[ -z "$HOST_ARCH" && -x "$EPICS_BASE/startup/EpicsHostArch" ]]; then
  HOST_ARCH="$("$EPICS_BASE/startup/EpicsHostArch")"
fi
if [[ -z "$HOST_ARCH" || ! -x "$IOC_DIR/bin/$HOST_ARCH/target" ]]; then
  echo "IOC target binary was not built for EPICS_HOST_ARCH=${HOST_ARCH:-unknown}." >&2
  exit 1
fi

ST_CMD="$IOC_DIR/iocBoot/ioctarget/st.cmd"
if [[ -f "$ST_CMD" ]]; then
  chmod +x "$ST_CMD"
  echo "Ensured IOC startup script is executable: $ST_CMD"
fi

echo "softIOC rebuild complete: $IOC_DIR/bin/$HOST_ARCH/target"
