#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/common.sh"

MACHINE_ID="${HALF_LINAC_MACHINE_ID:-half}"
EPICS_BASE_VALUE="${EPICS_BASE:-}"
BUILD=1

usage() {
  cat <<'EOF'
Usage: bash scripts/configure_softioc.sh [options]

Configure repository softIOC projects for the current computer and rebuild
them. The generated configure/RELEASE.local files are machine-local and ignored
by Git.

Options:
  --epics-base PATH       EPICS Base installation root.
  --machine half|irfel    Configure one machine (default: selected machine or half).
  --all                   Configure both half and irfel.
  --configure-only        Write local configuration without rebuilding.
  -h, --help              Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --epics-base)
      EPICS_BASE_VALUE="${2:-}"
      shift 2
      ;;
    --machine)
      MACHINE_ID="${2:-}"
      shift 2
      ;;
    --all)
      MACHINE_ID="all"
      shift
      ;;
    --configure-only)
      BUILD=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$EPICS_BASE_VALUE" ]] && command -v softIoc >/dev/null 2>&1; then
  SOFT_IOC_BIN="$(command -v softIoc)"
  EPICS_BASE_VALUE="$(cd "$(dirname "$SOFT_IOC_BIN")/../.." && pwd)"
fi

if [[ -z "$EPICS_BASE_VALUE" ]]; then
  echo "EPICS Base could not be detected." >&2
  echo "Pass --epics-base /path/to/epics-base or export EPICS_BASE." >&2
  exit 1
fi

EPICS_BASE_INPUT="$EPICS_BASE_VALUE"
EPICS_BASE_VALUE="$(cd "$EPICS_BASE_INPUT" 2>/dev/null && pwd)" || {
  echo "EPICS_BASE directory does not exist: $EPICS_BASE_INPUT" >&2
  exit 1
}
if [[ ! -f "$EPICS_BASE_VALUE/configure/CONFIG_BASE" ]]; then
  echo "Not an EPICS Base installation: $EPICS_BASE_VALUE" >&2
  exit 1
fi
if [[ ! -x "$EPICS_BASE_VALUE/startup/EpicsHostArch" ]]; then
  echo "EPICS Base is missing executable startup/EpicsHostArch." >&2
  exit 1
fi
if [[ "$EPICS_BASE_VALUE" =~ [[:space:]] ]]; then
  echo "EPICS Base paths containing whitespace are not supported by the EPICS build system." >&2
  exit 1
fi

HOST_ARCH="$("$EPICS_BASE_VALUE/startup/EpicsHostArch")"
if [[ ! -x "$EPICS_BASE_VALUE/bin/$HOST_ARCH/softIoc" ]]; then
  echo "EPICS Base has no softIoc for $HOST_ARCH. Build EPICS Base first." >&2
  exit 1
fi

case "$MACHINE_ID" in
  all) MACHINES=(half irfel) ;;
  half|irfel) MACHINES=("$MACHINE_ID") ;;
  *)
    echo "Unsupported machine: $MACHINE_ID (expected half, irfel, or --all)" >&2
    exit 2
    ;;
esac

for machine in "${MACHINES[@]}"; do
  IOC_DIR="$(
    python3 -c 'import sys; from half_linac.src.shared.machine_profile import resolve_machine_runtime; print(resolve_machine_runtime(sys.argv[1]).softioc.root)' "$machine"
  )"
  RELEASE_LOCAL="$IOC_DIR/configure/RELEASE.local"
  {
    echo "# Generated by scripts/configure_softioc.sh; do not commit."
    echo "EPICS_BASE = $EPICS_BASE_VALUE"
  } > "$RELEASE_LOCAL"
  echo "Configured $machine softIOC: $RELEASE_LOCAL"

  if [[ "$BUILD" -eq 1 ]]; then
    bash "$SCRIPT_DIR/build_ioc.sh" \
      --machine "$machine" \
      --epics-base "$EPICS_BASE_VALUE"
  fi
done

cat <<EOF

softIOC configuration complete.
EPICS_BASE=$EPICS_BASE_VALUE
EPICS_HOST_ARCH=$HOST_ARCH

Select a machine and start its IOC manager with:
  export HALF_LINAC_MACHINE_ID=${MACHINES[0]}
  export HALF_LINAC_CONTROL_BACKEND=vm
  bash scripts/start_ioc_manager.sh
EOF
